---
- name: Install RabbitMQ server
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: Create openstack user on RabbitMQ with the required privileges
  become: yes
  rabbitmq_user:
    user: openstack
    password: rabbitmq_password
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
